/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mostew.cityshoppingmc.Main;

import com.mostew.cityshoppingmc.Classes.Clothing;
import com.mostew.cityshoppingmc.Classes.DBManager;
import com.mostew.cityshoppingmc.Classes.Footwear;
import com.mostew.cityshoppingmc.Classes.GUI;

import java.util.HashMap;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mcarr
 */
public class GBrowseProducts extends javax.swing.JFrame
{

    DBManager db = new DBManager();

    GUI gui = new GUI();
    String action = "";
    String error = "EMPTY1971";
    HashMap<Integer, Clothing> clothes = new HashMap<>();
    HashMap<Integer, Footwear> shoes = new HashMap<>();

    int itemTaken;
    int columnNumber = 4;
    String columnName = "";

    /**
     * Creates new form ViewProducts
     */
    private void groupButton()
    {
        ButtonGroup bg2 = new ButtonGroup();
        bg2.add(rbClothing);
        bg2.add(rbFootwear);

    }

    public GBrowseProducts()
    {
        initComponents();
        groupButton();
        clothes = db.loadAllClothing();
        shoes = db.loadAllFootwear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        btnCHomePage = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        rbClothing = new javax.swing.JRadioButton();
        rbFootwear = new javax.swing.JRadioButton();
        comboQuantity = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listProducts = new javax.swing.JList<>();
        btnAddProducts = new javax.swing.JButton();
        lblResult = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCProducts = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCHomePage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCHomePage.setText("Return to Menu");
        btnCHomePage.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCHomePageActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Products");

        rbClothing.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbClothing.setText("Clothing");
        rbClothing.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rbClothingActionPerformed(evt);
            }
        });

        rbFootwear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbFootwear.setText("Footwear");
        rbFootwear.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rbFootwearActionPerformed(evt);
            }
        });

        comboQuantity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboQuantity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));
        comboQuantity.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                comboQuantityActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Quanity:");

        jScrollPane1.setViewportView(listProducts);

        btnAddProducts.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAddProducts.setText("Add to Basket");
        btnAddProducts.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAddProductsActionPerformed(evt);
            }
        });

        lblResult.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tblCProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "ProductID", "Product Name", "Price", "Stock Level", ""
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblCProducts);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCHomePage)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbFootwear)
                            .addComponent(rbClothing))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(33, 33, 33)
                                        .addComponent(comboQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnAddProducts)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCHomePage)
                    .addComponent(jLabel1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(rbClothing)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbFootwear)
                        .addGap(30, 359, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(comboQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAddProducts)
                                    .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbClothingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbClothingActionPerformed
        // TODO add your handling code here:
        columnName = "Measurement";
        gui.renameColumn(tblCProducts, columnNumber, columnName);
        clothes = db.loadAllClothing();
        DefaultTableModel dtm = (DefaultTableModel) tblCProducts.getModel();
        
        String[] data = new String[5];
        gui.populateClothes(data, clothes, dtm, tblCProducts);
    }//GEN-LAST:event_rbClothingActionPerformed

    private void rbFootwearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFootwearActionPerformed
        // TODO add your handling code here:
        columnName = "Size";
        gui.renameColumn(tblCProducts, columnNumber, columnName);
        shoes = db.loadAllFootwear();

        DefaultTableModel dtm = (DefaultTableModel) tblCProducts.getModel();
       

        String[] data = new String[5];
        gui.populateShoes(data, shoes, dtm, tblCProducts);
    }//GEN-LAST:event_rbFootwearActionPerformed

    private void comboQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboQuantityActionPerformed
        // TODO add your handling code here:

        DefaultComboBoxModel jcb = new DefaultComboBoxModel();
        jcb = (DefaultComboBoxModel) comboQuantity.getModel();
        String itemQ = (String) jcb.getSelectedItem();
        itemTaken = Integer.parseInt(itemQ);


    }//GEN-LAST:event_comboQuantityActionPerformed

    private void btnAddProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductsActionPerformed
        // TODO add your handling code here:

        boolean isClothing;

        action = "added";
        String guest = "Must be logged in to add products to basket. \nPlease login or register.";
        if (rbClothing.isSelected())
        {

            Clothing cloth = gui.findClothing(tblCProducts);
            isClothing = true;

            if (cloth.getProductName().equals(error))
            {
                gui.warning(lblResult, cloth, action);
            }
            else
            {
                if (itemTaken == 0 || cloth.getStockLevel() == 0)
                {
                    lblResult.setText("No clothing left in stock or quantity is equal to zero");
                }

                else if (cloth.getStockLevel() >= itemTaken)
                {
                    lblResult.setText(guest);
                }

                else
                {
                    lblResult.setText("Quantity selected is too high. Please select a smaller quantity");
                }
            }

        }

        else if (rbFootwear.isSelected())
        {

            Footwear shoe = gui.findFootwear(tblCProducts);
            //Clothing selected is false
            isClothing = false;
            if (shoe.getProductName().equals(error))
            {
                gui.warning(lblResult, shoe, action);
            }
            else
            {
                if (itemTaken == 0 || shoe.getStockLevel() == 0)
                {
                    lblResult.setText("No clothing left in stock or quantity is equal to zero.");
                }

                else if (shoe.getStockLevel() >= itemTaken)
                {

                    lblResult.setText(guest);

                }

                else if (itemTaken == 0)
                {
                    lblResult.setText("Please select a quantity greater than zero.");
                }

                else if (shoe.getStockLevel() == 0)
                {
                    lblResult.setText("Clothing out of stock");
                }

                else
                {
                    lblResult.setText("Please select a higher quantity.");
                }

            }

        }
        else
        {
            lblResult.setText("Clothing or footwear must be selected");
        }
    }//GEN-LAST:event_btnAddProductsActionPerformed

    private void btnCHomePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCHomePageActionPerformed
        // TODO add your handling code here:
        MenuGUI menu = new MenuGUI();
        this.dispose();
        menu.setVisible(true);
    }//GEN-LAST:event_btnCHomePageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(GBrowseProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(GBrowseProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(GBrowseProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(GBrowseProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new GBrowseProducts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProducts;
    private javax.swing.JButton btnCHomePage;
    private javax.swing.JComboBox<String> comboQuantity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblResult;
    private javax.swing.JList<String> listProducts;
    private javax.swing.JRadioButton rbClothing;
    private javax.swing.JRadioButton rbFootwear;
    private javax.swing.JTable tblCProducts;
    // End of variables declaration//GEN-END:variables
}
