/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mostew.cityshoppingmc.CustomerGUI;

import com.mostew.cityshoppingmc.Classes.*;

import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Date;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mcarr
 */
public class CViewOrderLines extends javax.swing.JFrame
{

    //Global Variables
    HashMap<Integer, OrderLine> oals = new HashMap<>();
    GUI gui = new GUI();
    OrderLine odl = new OrderLine();
    DBManager db = new DBManager();
    Customer cust = new Customer();
    double olTotal;
    String error = "EMPTY1971";
    NumberFormat decFormat = new DecimalFormat("#0.00");
    Order order = new Order();

    public CViewOrderLines()
    {
        initComponents();
        // Loads all the records that don't have an order ID
        oals = db.loadOrderLinesNoOrderID();

        //Creates a table model
        DefaultTableModel dtm = (DefaultTableModel) tblCOrderLine.getModel();
        
        // Creates a string array for the collumn
        // Populates the table by taking in four parameters a String array a hashmap, a default table model and the table
        String[] data = new String[4];
        gui.populateOrderLines(data, oals, dtm, tblCOrderLine);
        // Sets the total to zero
        olTotal = 0.00;
        // goes through all the orderlines and totals up the value
        for (OrderLine o : oals.values())
        {
            olTotal += o.getLineTotal();
        }
        // Convert the total into string format so I can display it
        // Also makes sure it's to 2 decimal places
        String sFormat = decFormat.format(olTotal);
        lblTotal.setText("£" + sFormat);
    }

    public CViewOrderLines(HashMap<Integer, OrderLine> orls, Customer c)
    {
        initComponents();
        // Loads all the records that don't have an order ID
        oals = db.loadOrderLinesNoOrderID();
        // loads the passed customer object and hashmap into global variables
        cust = c;
        // loads the customer from the database
        cust = db.loadCustomer(cust.getUsername());
        
        //Creates a table model
        DefaultTableModel dtm = (DefaultTableModel) tblCOrderLine.getModel();
         //gui.clearRows(dtm.getRowCount(), dtm);
        // Creates a string array for the collumns
        String[] data = new String[4];
         // Populates the table by taking in four parameters a String array a hashmap, a default table model and the table
        gui.populateOrderLines(data, oals, dtm, tblCOrderLine);
        
        // goes through all the orderlines and totals up the value
        for (OrderLine o : oals.values())
        {
            olTotal += o.getLineTotal();

        }
        // Convert the total into string format so I can display it
        // Also makes sure it's to 2 decimal places
        double formTotal = olTotal;
        String sFormat = decFormat.format(formTotal);
        lblTotal.setText("£" + sFormat);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        btnBrowseProducts = new javax.swing.JButton();
        btnBuy = new javax.swing.JButton();
        btnRemoveOrderLines = new javax.swing.JButton();
        lblResult = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCOrderLine = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBrowseProducts.setText("Return To Orders");
        btnBrowseProducts.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnBrowseProductsActionPerformed(evt);
            }
        });

        btnBuy.setText("Buy");
        btnBuy.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnBuyActionPerformed(evt);
            }
        });

        btnRemoveOrderLines.setText("Remove Selected Product");
        btnRemoveOrderLines.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRemoveOrderLinesActionPerformed(evt);
            }
        });

        lblResult.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setText("Order Line Total:");

        tblCOrderLine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Product ID", "Order Name ", "Quantity", "Total"
            }
        ));
        jScrollPane1.setViewportView(tblCOrderLine);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 13, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(btnBuy))
                                .addGap(18, 18, 18)
                                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRemoveOrderLines)))
                        .addGap(178, 178, 178))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBrowseProducts)
                        .addGap(55, 55, 55)
                        .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(btnBrowseProducts))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(btnBuy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemoveOrderLines)))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoveOrderLinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveOrderLinesActionPerformed
        // TODO add your handling code here:
        // selects the orderline you've selected from the table and converts it to an object
        odl = gui.findOrderLine(tblCOrderLine);
        // if there has been no selection
        if (odl.getProduct().getProductName().equals(error))//)
        {
            lblResult.setText("Cannot remove any items since orderline has not been selected");
        }
        else
        {

            
            // Once an orderline has been removed the orderline total decreases by the selected ordeline total
            olTotal -= odl.getLineTotal();
            
            // Once an orderline has been removed the stock changes
            // the stock level you reduced when you added it to your order line 
            // get put back to the product stock
            int stockBack = odl.getQuantity();
            Product prod = odl.getProduct();
            int currentStock = prod.getStockLevel();
            int ammendedStock = stockBack + currentStock;
            prod.setStockLevel(ammendedStock);
            //edits this change in the product database
            db.editProducts(prod);
            
            // updates the total in the lblTotal
            double formTotal = olTotal;
            // Formats it to 2 decimal places
            String sFormat = decFormat.format(formTotal);
            System.out.println(sFormat);
            // Deletes the selected orderline 
            db.deleteOrderLine(odl);
            //Loads the remaing orderlines with no ID
            oals = db.loadOrderLinesNoOrderID();
            lblTotal.setText("£" + sFormat);

            //Creates a default table model
            DefaultTableModel dtm = (DefaultTableModel) tblCOrderLine.getModel();
            // Creates a string array for the collumns
            String[] data = new String[4];
            // Populates the table by taking in four parameters a String array a hashmap, a default table model and the table
            gui.populateOrderLines(data, oals, dtm, tblCOrderLine);
           
        }


    }//GEN-LAST:event_btnRemoveOrderLinesActionPerformed

    private void btnBrowseProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseProductsActionPerformed
        // TODO add your handling code here:
        // Get the table model
        DefaultTableModel dtm = (DefaultTableModel) tblCOrderLine.getModel();
        
        // load a hashmap of orderlines with no orderID
        oals = db.loadOrderLinesNoOrderID();
        
        // if the hashmap isnt empty
        if (!oals.isEmpty())
        {
            // Create a date, status and create a new order object
            Date date = new Date();
            String status = "Incomplete";
            order = new Order(date, olTotal, status);

            // save the order to the database
            db.saveOrders(order, cust.getId());
            

        }
        // Passes the customer back to CBrowseProducts
        CBrowseProducts cbp = new CBrowseProducts(cust);
        this.dispose();
        cbp.setVisible(true);
    }//GEN-LAST:event_btnBrowseProductsActionPerformed

    private void btnBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyActionPerformed
        // TODO add your handling code here:
        // if there are no items
        if (olTotal == 0.00)
        {
            lblResult.setText("There are no items in your cart.");
        }
        else
        {
            // Create a hashmap and load orderlines that have no order ID into it
            HashMap<Integer, OrderLine> orderLines = new HashMap<>();
            orderLines = db.loadOrderLinesNoOrderID();
            // Create a new date set status to complete and set the total to the olTotal
            Date date = new Date();
            String status = "Complete";
            double total = olTotal;
            
            // Add an order object
            Order order = new Order(date, total, status);
            // save the order to the database
            db.saveOrders(order, cust.getId());
            // load the order object from the database
            order = db.loadOrder(order.getOrderDate());
            
            // Edit the order line to you assign the correct orderID for that orderLine
            db.editOrderOlsID(order.getOrderId(), orderLines);
            //Then load the orderline with no order ID
            orderLines = db.loadOrderLinesNoOrderID();
            
            //Creates a default table model
            DefaultTableModel dtm = (DefaultTableModel) tblCOrderLine.getModel();
            // Creates a string array for the collumns
            // Populates the table by taking in four parameters a String array a hashmap, a default table model and the table
            String[] data = new String[4];
            gui.populateOrderLines(data, orderLines, dtm, tblCOrderLine);
             // Sets the total to 0.00
            double olLTotal = 0.00;
            lblTotal.setText("£" + olLTotal);

        }


    }//GEN-LAST:event_btnBuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(CViewOrderLines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(CViewOrderLines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(CViewOrderLines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(CViewOrderLines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new CViewOrderLines().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowseProducts;
    private javax.swing.JButton btnBuy;
    private javax.swing.JButton btnRemoveOrderLines;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblCOrderLine;
    // End of variables declaration//GEN-END:variables
}
